### ISSUE TITLE
Trying to set a branch password crashes Meli

### ISSUE THREAD

**Issue by queicherius** [getmeli/meli#6] opened 2020-12-12 19:56 UTC
When I head over to a branch and check the "protected" box, and confirm the modal, Meli crashes with no logs and exit code 139 (running in Docker, on the `getmeli/meli:beta` image).

**Comment by gempain** [comment] 2020-12-13 14:53
@queicherius thanks for reporting, and sorry for the inconvenience. I'll check this right away and get back to you. i'll add this to the next release.

**Comment by gempain** [comment] 2020-12-13 16:37
@queicherius I can confirm this, it's odd, the container crashes right away and restarts. I tested with the development setup and it works, so I'm assuming this is related to Caddy and Meli being together inside the container. Investigating with @pimartin.

**Comment by gempain** [comment] 2020-12-13 18:18
The issue comes from bcrypt throwing an error and crashing Node when hashing the provided password. I'll fix this first thing tomorrow morning. Iv'e been wanting to drop `bcrypt` for `scrypt` for a while, because `scrypt` is natively supported by Node's `crypto` and Caddy supports it for basic auth, so I'll do both at once.

**Comment by gempain** [comment] 2020-12-14 16:32
@queicherius this fix was released in v1.0.0-beta.5. We dropped bcrypt and now use scrypt. Note that we removed the `MELI_BCRYPT_SALT_ROUNDS` environment variable, but I doubt you used it. I'm closing, but you may continue to reply if further help is required. We'll reopen if needed. Again, many thanks for contributing to this project.

**Closed as completed by gempain** 2020-12-14 16:32 UTC
Labels: bug
